/**
 * 
 */
define({
	
	//added search sequence number
	searchSequence:"Search",
	searchSeqNumber:"Search Sequence Number",
	RIGHT_SCAN_BLACK:"RIGHT SCAN BLACK",
	RIGHT_SCAN_GRAY:"RIGHT SCAN GRAY",
	RIGHT_SCAN_COLOR:"RIGHT SCAN COLOR",
	RIGHT_SEND_OUTGOING_WITH_OLD_DATE:"RIGHT SEND OUTGOING WITH OLD_DATE",
	RIGHT_CREATE_GENERALIZATIONS:"RIGHT CREATE GENERALIZATIONS",
	RIGHT_SEND_WITHOUT_ATTACHMENTS:"RIGHT SEND WITHOUT ATTACHMENTS",
	RIGHT_CREATE_STATISTICAL_REPORTS:"RIGHT CREATE STATISTICAL REPORTS",
	RIGHT_FOLLOWUP_REMINDER:"RIGHT FOLLOWUP REMINDER",
	RIGHT_DEPT_SEARCH_OPTION:"RIGHT DEPT SEARCH OPTION",
	RIGHT_MAIN_DEPARTMENT_MANAGER:"RIGHT MAIN DEPARTMENT MANAGER",
	RIGHT_EDIT_OUTGOING:"RIGHT EDIT OUTGOING",
	RIGHT_EDIT_INCOMING:"RIGHT EDIT INCOMING",
	RIGHT_EDIT_INTERNAL:"RIGHT EDIT INTERNAL",
	RIGHT_FULL_SEARCH_OPTION:"RIGHT FULL SEARCH OPTION",
	RIGHT_MANAGER_PERMISSION:"RIGHT MANAGER PERMISSION",
	RIGHT_SHOW_CONFIDENTIALITY_SECURE:"RIGHT SHOW CONFIDENTIALITY SECURE",
	RIGHT_SHOW_CONFIDENTIALITY_VERY_SECURE:"RIGHT SHOW CONFIDENTIALITY VERY SECURE",
	RIGHT_SHOW_CONFIDENTIALITY_EXTREME_SECURE:"RIGHT SHOW CONFIDENTIALITY EXTREME SECURE",
	RIGHT_COMMUNICATE_ALL_EMPLOYEE:"RIGHT COMMUNICATE ALL EMPLOYEE",
	RIGHT_EDIT_CORR_DETAILS:"RIGHT EDIT CORR DETAILS",
	RIGHT_EDIT_CORR_ATTACHMENTS:"RIGHT EDIT CORR ATTACHMENTS",
	RIGHT_EDIT_CORR_RESEND:"RIGHT EDIT CORR RESEND",
	RIGHT_END_CORRESPONDENCE:"RIGHT END CORRESPONDENCE",
	RIGHT_DELETE_HISTORY_AND_WORITEMS:"RIGHT DELETE HISTORY AND WORITEMS",
	RIGHT_REMINDER_MESSAGE:"RIGHT REMINDER MESSAGE",
	RIGHT_DEADLINE:"RIGHT DEADLINE",
	RIGHT_EXPORT:"RIGHT EXPORT",
	RIGHT_CREATE_OUTGOING:"RIGHT CREATE OUTGOING",
	RIGHT_CREATE_INCOMING:"RIGHT CREATE INCOMING",
	RIGHT_CREATE_INTERNAL:"RIGHT CREATE INTERNAL",
	RIGHT_Department_Represented:"RIGHT Department Represented",
	RIGHT_CREATE_DECESIONS:"RIGHT CREATE DECESIONS",
	RIGHT_CREATE_CIRCULARS:"RIGHT CREATE CIRCULARS",
	canAccessSystemLable:"Can Access System?",	
	ldap_inquiry:"LDAP Inquiry",	
	Employee_Infomration:"Employee Information",
	Powers_Granted:"Powers Granted",	
	Customized_Forwarding_List:"Customized Forwarding",
	substitute_employee:"Substitute Employee",
	Records_Management:"Employees/Departments",
	ManageEmployees: "Manage Employees",
	InbasketMembers:"Inbasket Members",
	ManagePublicInbasketMembers:"Manage Public Inbasket Members",
	ManagePublicInbasket:"Manage Public Inbasket",
	PublicInbasket:"Public Inbasket",
	DeptsAdministration:"Manage Departments",
	Committees_Management:"Committees",
	CommitteesAdministration:"Manage Committees",
	CommitteesMembers_Administration:"Manage Committees Members",
	CommiteeMembers:"Commitee' Members",
	GROUPID:"Group Code",
	GROUPNAME:"Group Name",
	GroupMembers:"Group Members",
	Group_Management:"Group",
	ManageGroups:"Manage Groups",
	ManageGroupMembers:"Manage Group' Members",
	ManageDestination:"Manage Destinations",
	ManagePhysicalAttachments:"Manage Physical Attachments Types",
	ManageBarcode:"Manage Barcode",
	ManageReportBanners:"Manage Report Banners",
	destinationID:"Destination ID",
	DestinationNAME:"Destination NAME",
	DestinationTYPE:"Destination TYPE",
	committeeDescription:"Committee Description",
	ManageApplicationLables:"Manage Application Lables",
	ManageMessages:"Manage Application Messages",
	ManageInboxSettingColorsHTML:"Manage Inbox Setting Colors",
	
	User_List:"New Users List",
	UserList_setIntroText:"A Description for New Users List",
	SubjectID:"Subject ID",
	SubjectText:"Subject Text",
	EmployeeID:"Employee ID",
	EmployeeName:"Employee Name",
	InstructionID:"Instruction ID",
	InstructionText:"Instruction Text",
	AttachmentID:"Attachment Code",
	AttachmentText:"Attachment Type",
	Othertables:"Manage Application Data",
	ManageSubjects:"Manage Subjects Text",
	ManageInstructions:"Manage Instructions Text",
	This_Correspondance_is_not_exist:"This Correspondance is not exist",
	Error_Title:"Error Message",
	ExportCOnfimrationlable:"Ok",	
	AreYouShureToExportCorrespondfance:"Are You sure you want to export this Correspondance to the selected destination",
	Cancelof_ExportCOnfimrationlable:"Cancel",
	ConfirmationTitle:"Confirmation on Exporting the Correspondance",
	Notfication_ConfirmationTitle:"Confirmation on Notfication",
	Notfication_Mesage_Keep_Yes_No:"This Notfication Message is going to be removed from your personal Inbox, Press Cancel if you want to keep it",
	
		Inbox_Settings_has_been_saved_sucessfully:"Inbox Settings has been saved sucessfully",
	
	The_Internal_Correspondance_with_No:"The Internal Correspondance with Number",
	The_Circulating_Correspondance_with_No: "The Circulating Correspondance with Number",
	The_Decision_Correspondance_with_No: "The Decision Correspondance with Number",
	Correspondence_Successfully_Exported	:"has been Successfully Exported as Outgoing with Outgoing Correspondance Number",
	Correspondence_is_already_Exported:"Correspondence has been already exported ",
	ExportStatus:"The Export Status",
	Do_You_Want_to_Open_exported_Correspondance:"Do You Want to view the exported Correspondance ",
	Yes_Confimration:"Yes",
	No_Confimration:"No",
	and_Number:"Number",
	and_Date:"and Date",
	and_year:"and year",
	error_on_Select_TO_Date:"Error on Select TO Date",
	error_on_Select_From_Date:"Error on Select From Date",
	error_on_Select_The_Observer_from_The_List:"Error on Select The Observer from The List",
	error_on_Select_Followup_CheckList:"Error on Select Followup Checkbox",
	error_on_Select_Delegating_Check:"Error on Select Delegating Checkbox",
	
	error_no_Outgoing_transfered_workflow_found : "There is an error , as no transfered workflow found for Outgoing process",
	error_no_Incoming_transfered_workflow_found : "There is an error , as no transfered workflow found for Incoming process",
	error_no_Internal_transfered_workflow_found : "There is an error , as no transfered workflow found for Internal process",
	error_URL_parameter_for_Outgoing_workClassName_is_missing:"URL parameter for Outgoing workClassName is missing",
	error_URL_parameter_for_Incoming_workClassName_is_missing:"URL parameter for Incoming workClassName is missing",
	error_URL_parameter_for_Internal_workClassName_is_missing:"URL parameter for Intyernal workClassName is missing",
	error_Message_for_export_did_not_Add_any_destination:"There is an error , as you have not chosed any Destination",
	
	error_Can_not_Delete_Employee_Still_Has_Correspondance_in_his_inbox:"There is an error ,Cannot delete this employee since he still has Correspondence in his inbox which has not been completed yet!!",
			error_Can_not_Delete_Employee_He_Has_Backup:"There is an error ,Cannot delete this employee since he has Backup !!",
		error_Can_not_Delete_Employee_He_is_a_Backup:"There is an error ,Cannot delete this employee since he is Backup to other employee",
			error_Can_not_Delete_Employee_He_is_a_Manager:"There is an error ,Cannot delete this employee since he is Manager to other employees, you need first to rAssign other employee as manager to his department first",
		error_Can_not_Delete_Employee_He_is_a_member_of_community_or_more:"There is an error ,Cannot delete this employee since he is currently member of one or more communities",
			processRoleName:"Moamalat Inbox",
	appSpaceName:"Moamalat Application Spaces",
	inboxQueueName:"My Inbox",
	OutgoingDestinations:"Outgoing Destinations",
	Add_another_OutgoingDestinations:"Select Another Outgoing Destinations",
	Exit:"Exit",
	Incoming_correspondence_hlabel:"Incoming",
	outgoing_correspondence_hlabel:"outgoing",
	Internal_correspondence_hlabel:"Internal",
	AddToDestination:"Add to destination",
	DestinationName:" Destination Name",
	SentVia:"Send By",
	letterType:"Letter Type",
	ExternalUnits:"External Units",
	ExternalGroups:"External Groups",
	ExportCorrepsondence:"Export Correspondence",
	Details:"Details",
	Print_Enquiry_Ticket:"Printing Enquiry Ticket",
	Source:"Source",
	Forwarding_Details:"Forwarding Details",
	ReadTask:"True",
	unReadTask:"False",
	update:"Update",
	Incoming_correspondence:"Incoming Correspondence",
	outgoing_correspondence:"outgoing Correspondence",
	Internal_correspondence:"Internal Correspondence",
	Decision:"Decision",
	Reminder_for_incoming:"Reminder for incoming",
	Reminder_for_outgoing:"Reminder for outgoing",
	Reminder_for_internal:"Reminder for internal",
	CC_for_incoming:"CC for incoming",
	CC_for_outgoing:"CC for outgoing",
	CC_for_internal:"CC for internal",
	Read_response_notification:"Read response notification",
	urgent:"Urgent",
	topurgent:"Top Urgent",
	important:"Important",
	Reminder:"Reminder",
	ccCorresp:"CC Correspondence",
	completed:"Completed",
	Inprogress:"In Progress",
	newCr:"New",
	circulation:"Circulation",
	Geneate_print_barcode:"Print Barcode label",
	GenerateBarcode_label:"Print BarCode",
	Geneate_Print_Barcode_For_Correspondence:"Generate and Print barcode",
	correspondance_Type: "Correspondance Type",
	Readresponse_Message_Word1_for_INCOMING:"The Incoming Currespondance",
	Readresponse_Message_Unknown_Currespondance_Type:"The Currespondance",
	Readresponse_Message_Word1_for_OUTGOING:"The Outgoing Currespondance",
	referenced_correspondence:"referenced correspondence",
	Label_Internal_Outgoing:"Internal Outgoing No",
	Label_Correspondence_Date:"Correspondence Date",
	Label_Attachments:"Attachments",
	Print:"Print",
	Readresponse_Message_Word1:"The Internal Currespondance",
	Readresponse_Message_Word2 :"with Number",
	Readresponse_Message_Word3:"and subject",
	Readresponse_Message_Word4 :"has already been read from User",
	Readresponse_Message_Word5:"on date",
	Readresponse_Message_Word6:"and time",
	CurrentSystemDateisnotHijiry:"Please Change the date type to  UmmAlQura Type",
	SourceIncomingcorrespondenceUmmAlQuraDateIsNotSelected:"Please enter the Source Incoming Date",
	Incomming_From_Is_Empty:"Incomming-From has't been selected",
	Incomming_Forward_to_Is_Empty:"Forward to has not been selected",
	forward_to_outgoing_Is_Missing:"forward-to has not been selected from the list",
	Prepared_Departmenet_Is_Missing:"Prepared Department has not been selected from the list",
	DeliveryReportNoLable:"Delivery Report No",	
	Normal:"Normal",
	Secret:"Secret",
	top_secret:"Top Secret",
	extremely_confidential:"Extremely Confidential",
	Physical_Attachmenet_type:"Type of Physical Attachmenet ",
	Quantity:"Quantity",
	Comments:"Comments",
	No:"No",
	Physical_Attachmenet:"Physical_Attachmenet",
	Physical_Attachmenet_Add:"ِAdd Physical Attachmenets",
	test_messsage_error: "test   error   bashar",
	test_messsage_error_explanation: "test explanation",
	test_messsage_error_userResponse: "test userResponse",
	To_Date_Has_not_selected:"To Date has not selected ",
	From_Date_Has_not_selected:"From Date has not selected",
	error_item_is_exist:"item is already exist in the Grid",
	
	correspondence_subject_label : "Correspondence Subject",
			CirculateCorrespondence_subject_label:"Circulate Subject",
	DecisionCorrespondence_subject_label:"Decision Subject",
	
	Outgoing_correspondence_subject_label : "Outgoing Correspondence Subject",
	Incoming_correspondence_subject_label : "Incoming Correspondence Subject",
	correspondence_no_label : "Correspondence No",
	
		Decision_correspondence_no_label:"Decision No",
	Decision_correspondence_date_label :"Decision Date",
	Decision_correspondence_type_label :"Decision Type",
	Decision_correspondence_category_label :"Decision Category",
	
	Circulate_correspondence_no_label:"Circulate No",
	Circulate_correspondence_date_label :"Circulate Date",
	Circulate_correspondence_type_label :"Circulate Type",
	Circulate_correspondence_category_label :"Circulate Category",
	
	
	
	
	
	correspondence_date_label : "Correspondence Date",
	Source_Outgoing_correspondence_date_label:"Source correspondence date",
	correspondence_type_label : "Correspondence Type",
	correspondence_category_label : "Correspondence Category",
	confidentiality_label : "Confidentiality",
	prepared_by_label : "Prepared By",
	created_by_label : "Created By",
	send_by_label : "Send By",
	exported_to_label:"Exported To",
	physical_attachments_label : "Physical Attachments",
	referenced_correspondence_label : "Referenced Correspondence",
	remarks_label : "Remarks",
	incoming_correspondence_information_label : "Incoming Correspondence Information",
	internal_correspondence_information_label : "Internal Correspondence Information",
	circulate_correspondence_information_label : "Circulate Correspondence Information",
	decision_correspondence_information_label : "Decision Correspondence Information",
	outgoing_correspondence_information_label : "Outgoing Correspondence Information",
	attachments_label : "Attachments",
	action_label : "Action",
	process_attachments: "Attachments",
	Lunch_Correspondence : "Send",
	Save_Correspondence : "Save",
	Process_Correspondence : "Complete",
	Electronic_Attachments : "Electronic Attachments",
	FilteringSelect_placeholder : "select or enter characterSet",
	FilteringSObserver_placeholder:"Select the Observer",
	created_by_placeholder:"Select who create it ",
	correspondence_date_placeholder:"Select the Date",
	correspondence_type_placeholder:"to select the type of this correspondence from the list",
	correspondence_category_placeholder:"to slect the category of this correspondence from the list",
	confidentiality_placeholder: "to slect the confidentiality of this correspondence from the list",
	prepared_by_placeholder:"to slect who prepare this correspondence from the list",
	Decision_label:"ِAction Type",
	Priority_label:"Priority",
	Normal_option:"Normal",
	Urgent_option:"Urgent",
	TopUrgent_option:"TopUrgent",
	Deadline_label:"Deadline",
	SetDeadlineAfter_label:"Set Deadline After",
	Reminder_label:"Reminder",
	SetReminderafter_label:"Set Reminder After",
	Followup_label:"Followup ",
	From_label:"From",
	followupto_label:"To",
	Important_CheckBox:"Important",
	RequestReadResponse_checkbox:"Request Read Notfication",
	Orgnication_Structure_per_Permissions_you_have_label:"Hierarchy Organization Structure per Permissions you have",
	Orgnization_All_Structure_Tab:"All Departments",
	Employees_of_the_Selected_Departmenet:" Employees per the Selected Department",
	Forward_To_Emloyees:"Forward To Employee",
	Cc_to_Emloyees:"Cc to Employee",
	Cc:"Cc",
	TO:"To",
	to_both_Types:"Both",
	Observer:"Observer",
	Observer_Followup_Correspondence:"Asign Observer or Followup",
	Instruction_to :"Instruction To :",
	Draft_Instructions :"Predefined Instructions",
	Predefined_Select_Instructions:"Select",
	Predefined_Manage_Instructions  :"Manage Instructions",
	Edit_Instructions  :"Edit Instructions",
	Add:"Add",
	Remove:"Remove",
	User_ID:"User ID",
	User_Name:"User Name",
	Dept_Name: "Department Name",
	Instruction:"Instruction",
	Forwarding_Type:"Forwarding Type",
	userId 	:"User ID",
	employeeId :"Employee Id",
	nationalNumber :"National Number",
	fullName : "LDAB User Name",
	departmentId : "Department ID",
	departmentName : "Department Name",
	managerId : "Manager ID",
	managerName:"Department Manager Name",
	MANAGER_FULL_NAME_AR:"Manager Name",
	parentDepartmentId : "Parent Department ID",
	jobTitle : "JOb Title",
	isActive : "IS Active",
	emp_Email : "Email",
	emp_Mobile : "Mobile",
	specfialization : "Specialization",
	qualification :"Qualification",
	degree : "ُEmployee Degree",
	enabledOptionsMask : "Enable Option Mask",
	departmentCode : "Department Code",
	forwaringToListType : "Forwarding To List Type",
	backupEmployee : "Backup Employee",
	backupUserid : "Backup User Id", 
	backupStartDate : "Backup Start Date",
	backupEndDate : "Backup End Date",
	queueName:"Queue Code",
	Has_backupEmployee:"Has A Backup ",
		backupEMPFullName:"Backup Employee Full Name",
	managerUserId:"Manager User ID",
	managerFullName:"Manager Full Name",
	representativeFullName:"Representative Full Name",
	departmentLevel:"Department Level or Type",
	departmentQueueName_English_Lable:"Shared In-Basket(English Name)",
	departmentQueueName_Arabic_Lable:"Shared In-Basket(Arabic Name)",
	QueueNameCodeLable: "In-Basket Code",
	DepartmentTab_Information:"Department Information",
	Employees_of_the_Selected_Departmenet:"Department Employees",
	Grant_Permision:"Grant Permision",
	Inbasket_Members:"Public Inbasket Members",
	ApplicationSpaces_Lable	:"Application Spaces",	
	RolesName_English_Lable:"Role (English Name)", 
	RolesName_Arabic_Lable:"Role (Arabic Name)",
	ROLE_Text:"Role For ",
	WorkQueues_Lable:"Work Queues",
	enable_Shared_Inbasket_lable:"Enable Shared Inbasket for this Department",
	Shared_Inbasket:"Shared Inbasket",
	COMMITTEEID:"Committee Id",
	COMMITTEENAME:"Committee Name",
	STARTDATE:"Start Date",
	ENDDATE:"End Date",
	PRESIDENTID:"President Id",
	PRESIDENTNAME:"President Name",
	EmployeeName:"Employee Name",
	EmployeeList:"Employee List",
	Actions_for_Internal_Correspondence:"Actions for Internal Correspondence ",
	Actions_for_Circular_Correspondence:"Actions for Circular Correspondence ",
	Actions_for_Decision_Correspondence:"Actions for Decision Correspondence ",
	
	
	Instructions_for_Internal_Correspondence:"Users’ Instructions for Internal Correspondence",
	Instructions_for_Circular_Correspondence:"Users’ Instructions for Circular Correspondence",
	
	
	Instructions_for_Decision_Correspondence:"Instructions for Decision Correspondence",
	
	
	
	Actions_for_Incoming_Correspondence:"Actions for Incoming Correspondence ",
	Actions_for_Outgoing_Correspondence:"Actions for Outgoing Correspondence ",
	
	Instructions_for_Incoming_Correspondence:"Users’ Instructions for Incoming Correspondence",
	Instructions_for_Outgoing_Correspondence:"Users’ Instructions for Outgoing Correspondence",
	
	
	InstructionsToSpecficUsers_option:"Specific Users .",
	InstructionsToAllUsers_option:"All Users .",
	Specfy_Instructions_to_Forwarded_Emloyees:"Selected Forwarded Emloyees",
	Specfy_Instructions_to_Cced_Emloyees:"Selected Copied Emloyees",
	codeTitle:"Code",
	IncludeTitle:"Include",
	Currepondance_is_created :"Currepondance is saved successfully..",
	Currepondance_is_updated :"Currepondance is updated  successfully..",
	Deadline_time_Type_is_Empty:"Deadline time Type is Empty",
	Deadline_time_Number_is_Empty:"Deadline time Number is Empty",
	Enter_Currrespondance_Subject :"Enter Currrespondance Subject ",
	Reminder_TIme_Type_is_Empty:"Reminder TIme Type is Empty",
	Reminder_Time_Number_is_Empty:"Reminder Time Number is Empty",
	Already_Security_is_applied_for_this_correspondence:" Security has been already applied for this correspondence",
	Security_Successfully_Applied_on_correspondence:"Security successfully applied on correspondence",
	you_have_already_added_this_Please_select_different_physical_attachment:"You have already added this infromation , you can add other different physical attachments",
	you_have_already_added_this_Please_select_different_Destination:"You have already added this infromation , you can add other different Destination",
	Select_To_Users:"You need to select at least one of the Users / Departments who want to forward the Correspondence to ", 
	Select_Cc_Users:"You need to select at least one of the Users / Departments who want to copy the Correspondence to ", 
	HIS_FROM : "From",
	HIS_TO : "To",
	HIS_CC : "CC",
	HIS_TIME : "Action Time",
	HIS_ACTIONS : "Actions",
	HIS_IMP : "Important",
	HIS_CONF : "Confidential",
	HIS_URG : "Urgent",
	HIS_TOP_URG : "Top Urgent",
	HIS_REMARKS : "Remarks",
	History_label:"History Page",
	add_document_scan_label : "Scan Document",
	add_document_scan_button : "Scan",
	add_document_scan_entery_label : "Scan Document by Using Entry Template",
	Outgoing_Forward_to:"Forward To",
	Request_Printing_Gregorian_Date_in_BarCode_Label:"Printing Gregorian Date in BarCode",
	Request_Printing_Statement_delivery:"Print Statement Delivery",
	Create_Printing_Statement_delivery:"Create & Print Statement Delivery",
	Internal_Label:"Internal Outgoing",
	Decision_label_No:"Decision No",
	Internal_Date_Lable:"Internal Date",
	Circular_Date_Lable:"Circular Date",
	CIRCULAR_Label:"Circular No",
	Incoming_Label:"Incoming No",
	Incoming_No:"Incoming Number",
	Incoming_Date_Lable:"Incoming Date",
	Decision_Date_Lable:"Decision Date",
	Outgoing_Label:"Outgoing No",
	Outgoing_Date_Lable:"Outgoing Date",
	export_by_label:"Export by",
	Details:"Details",
	recieved_on_date:"Recieved On Date",
	added_on_date:"added on Date",
	correspondent_Courier_Name:"Name of correspondent'Courier ",
	Source_Outgoing_Correspondence_Number_label:"Source Outgoing No/ Al-Qayd-No",
	Source_Outgoing_correspondence_date_label:"Source Outgoing Date",
	Source_Incomming_From:"Incoming From",
	Forward_to_departmenet:"Forward to",
	Receipt_Way:"Receipt Way",
	Sender_Deatils:"Sender Deatils",
	Sender_MobileNumber:"Sender Mobile Number",
	Sender_email:"Sender Email",
	Commerce_Record:"Commerce Record",
	Civil_Record:"Civil Record",
	SHOW_OUTGOING_MAPPING :"Call / Mapp Correspondance",
	SHOW_INCOMING_MAPPING   :"Call Incoming Correspondance",
	SEARCH_CORRES_HIJRIC_YEAR  :"Hijric Year",
	SEARCH_CORRES_NUMBER  :"Correspondance Number",
	CALL  :"Call",
	btnClear  :"Clear",
	
	btnNew:"New",
	btnOK:"OK",
	SEARCH_CORRES_TYPE  :"Correspondance Type",
	TASDIED_INCOMING  :"Reply(Tasteed) to an Incoming Correspondance",
	TASDIED_OUTGOING  :"Reply(Tasteed) to an outgoing Correspondance",
	TASDIED_INTERNAL  :"Reply(Tasteed) to an Internal Correspondance",
	CALL_OUTGOING  	  :"CallBack an Outgoing Correspondance",
	MAPPING  :"Mapping",
	RELATION_TYPE_NEW : "New",
	RELATION_TYPE_REPLY : "Reply",
	RELATION_TYPE_FOLLOWUP : "Followup",
	RELATION_TYPE_ADDITION : "Addition",
	RELATION_TYPE_EXPORT : "Export",
	RELATIONS:"Correspondence Relation",
	
	Open_Related_Correspondance:"Display Related Correspondance",
	REM_NO : "No",
	SEARCH_CORRES_NUMBER : "Correspondences No.",
	SEARCH_CORRES_HIJRIC_YEAR : "Hijri Year",
	RELATION_CORRES_TYPE:"Correspondence Type",	
	RELATION_TYPE:"Relation Type",	
	DragDrop_Title:"Drag & Drop",
	submit_dragdrop:"Add",
	dragdrop_setIntroText:"The basic sequence involved in drag and drop is first to Move the pointer to the object file .and then to Press, and hold down on the right button on the mouse then  to grab  the file by draging it to the desired location by moving the pointer spefic location  and Drop the files by releasing the button, finally to  click Add in order to submit the objects as Attachments to the Correspondance",
	Subject_ID:"ID",
	SubjectNeedToModfied:"For Updating Subject Text",	
	Subject_New_Text:"ٍAdding new Subject",
	Manage_Subjects:"Manage Subjects",
	SubjectList:"ٍSubjects List",
	Subject:"Subject",
	Update:"Update",
	Delete:"Delete",
	new_internal:"Internal",
new_incoming:"Incoming",
new_outgoing:"Outgoing",
new_decision:"Decision",
new_circulate:"Circulate",
Inbox_Settings:"Indicator Color for Correspondance Priority in Inbox",


Pick_background_color_for_normal_work_items:"Pick color Indicator for normal Correspondances",
Pick_background_color_for_Urgent_work_items:"Pick color Indicator for Urgent Correspondances",
Pick_background_color_for_Top_Urgent_work_items:"Pick color Indicator for Top Urgent Correspondances",
	
	MoamalatWelcomeMessage:"Welcome To Admin Communication System ~ Moamalat",
Out_Of_Office_With_Delegate:"Out Of Office /Delgating to Another Employee",
Out_Of_Office_With_Delegate_setIntroText:"To Indicate that you are out of the office with specific Date with ability to delegate another Employee to receive your work while you are out of office. When you return to the office before date, you must clear this setting to resume receiving work. Until you clear the setting, the designated Employee will recieve your work.",

Delegaing:"Delegaing To",
	Save:"Save",
	
StopDelegating:"Stop Delegating",
	StartDelegating:"Delegate",
	
	
	AreYouShureTo_Cancel_Delegation:"Are You sure to Cancel Delegation and come back to work",
	ConfirmationTitle_Cancel_Delegation:"Confirmation on Coming Back to Office",
	OK_to_Cancel_Delegating_Button_Desc:"Ok",	
	Cancelof_Cancel_Delegating_Button_Desc:"No",
	
	AreYouShureTo_Delegate_your_Work:"Are You sure to Enable Delegation and going out of office",
	ConfirmationTitle_Enable_Delegation:"Confirmation on Going out off Office",
	OK_on_Delegating_Button_Desc:"Ok",
	Cancelof_Delegating_Button_Desc:"No",
	
	CIF_NO: "CIF NO",
			BRANCH: "BRANCH",
				FIRST_NAME: "FIRST NAME",
					LAST_NAME: "LAST NAME",
						NATIONALITY: "NATIONALITY",
							ID_TYPE: "ID TYPE",
							ID_NUMBER:"ID NUMBER",
							ACCOUNT_NO:"ACCOUNT NO",
								ID_DATE:"ID DATE",
	
					Lunch_Process:"Lunch Process",
					
		
StepProcessor_Fawri_Workflow : "Process Fawri Workflow",
	StepProcessor_StepProcessor_Fawri_Workflow_setIntroText : "to select the action required to process the Fawri  based on the properties",				
					
			F_OriginatorDisplayName:"Started by",
F_StepName:"Step",

F_StepReceived:"Recieved on",
F_Subject:"Subject",		
	FawriRemark:"Notes",
Branch_Notes:"Branch Notes",		
	Branch_Manager_Notes:"Branch Manager Notes",


	F_Deadline:"Due date",
	Main_Branch_Notes:"Main Branch Notes",
		Main_Branch_Manager_Notes:"Main Branch Manager Notes",
			FawriWelcomeMessage:"Welcome To Fawri",
		




	// tooltip
	
			HLP_correspondence_subject_label:"Text to describe Correspondence content",
			HLP_correspondence_no_label:"No. reserved for correspondence",
			HLP_correspondence_type_label:"Correspondence type such as Internal, incoming ...etc",
			HLP_correspondence_date_label:"Date of establishment correspondence",
			HLP_correspondence_category_label:"Correspondence Description",
			HLP_confidentiality_label:"security of correspondence for some employees",
			HLP_prepared_by_label:"Department whose  prepared the correspondence",
			HLP_physical_attachments_label:"Physical Attachments(as CD, book)",
			HLP_created_by_label:"User whose created the correspondence(AutoText)",
			HLP_remarks_label:"Text aria for adding notes about Correspondence",
			
			HLP_Subject_New_Text:"Add new correspondence subject",
			HLP_SubjectNeedToModfied:"Modify predefined correspondence subject",
			
			HLP_Decision_label:"Action type for correspondence",
			HLP_SetReminderafter_label:"Alert correspondent If no action on correspondence",
			HLP_Followup_label:"Follow-up correspondence From beginning to the end",
			HLP_Priority_label:"Determine correspondence priority",
			HLP_SetDeadlineAfter_label:"specific time to finish the work on correspondence",
			HLP_RequestReadResponse_label:"(Attention) Notice to reserved correspondence",
			HLP_Important_CheckBox:"Attention The importance of correspondence",
			HLP_Source_Outgoing_correspondence_date_label:"Date of issuance of Correspondence It is used to search for correspondence",
			HLP_Source_Outgoing_Correspondence_Number_label:"Number the exporter of Correspondence",
			HLP_Source_Incomming_From:"The exporter of Correspondence to external",
			HLP_Civil_Record:"Number ID of intended destination",
			HLP_Sender_MobileNumber:"Phone number of intended destination",
			HLP_Receipt_Way:"Options to determine the receiving",
			HLP_Sender_Deatils:"Notes about intended destination",
			HLP_Commerce_Record:"Text for description intended destination",
			HLP_Sender_email:"Text for description intended destination",
			HLP_Forward_to_departmenet:"Correspondence to external",
			HLP_Create_Printing_Statement_delivery:"attachment file",
			HLP_letterType:"Correspondence type",
			HLP_Details:"Detailed text content of the correspondence",
			HLP_SentVia:"Send correspondence type Multiple options",
			HLP_export_by_label:"نص تلقائي ثابت يبين اسم الموظف المنشأ للمعاملة",
			HLP_Request_Printing_Gregorian_Date_in_BarCode_Label:"ظهور التاريخ الميلاد في الباركود",
			HLP_SHOW_INCOMING_MAPPING:"Create correspondence",
			HLP_SEARCH_CORRES_HIJRIC_YEAR:"Date of establishment correspondence",
			
			HLP_withatachmnet:"with attachment",
		
			HLP_codeTitle:"Code to choose from list for facilitate departments selection",
			HLP_IncludeTitle:"All departments appear on the list as soon as writing Any letters of Department Name",
			HLP_Instruction_to:"Give instruction to employees",
			HLP_Draft_Instructions:"Choose from predefined instructions",
			HLP_Manage_Instruction:"To add Instructions on the drop-down list",
			HLP_Observer:"Choose Observer Correspondence to find out Where correspondence",
			HLP_DestinationName:"Issuer Name her correspondence outward",
			HLP_Label_Attachments:"Attachment file in correspondence ",
			HLP_Physical_Attachmenet_type:"Tangible attachment Type (such as CD ...etc)",
			HLP_Quantity:"number of tangible attachments",
			HLP_Comments:"write note to tangible attachment ",


		
		//Search Page
			HLP_SEARCH_BARCODE:"Search direct using barcod",
			HLP_SEARCH_CORRES_TYPE:"Type of correspondence (Internal, Incoming, Outgoing ...etc)",
			HLP_SEARCH_CORRES_NUMBER:"Number of correspondence you need to search for",
			HLP_SEARCH_CORRES_SUBJECT:"Text to describe Correspondence content used for search",
			HLP_SEARCH_FIND_IN:"To search in more than Department",
			HLP_SEARCH_STATUS:"Completed or not complete Correspondence",
			HLP_SEARCH_CORRES_DATE:"Date of establishment correspondence, used for search",
			HLP_SEARCH_FROM_DATE:"The start date search",
			HLP_SEARCH_TO_DATE:"The end date search",
			HLP_GEN_CORR_TYPE:"Correspondence type, used for search",
			HLP_GEN_CORR_CATEGORY:"Description correspondence, used for search",
			HLP_FROM_DETAILS:"User whose created the correspondence Used for search",
			HLP_SENT_BY:"Sent by, show module correspondence(Automatically shows )",
			HLP_SEARCH_TO_UNIT:"Directed to, show module correspondence(Automatically shows )",
			
		//Admin
			//Manage Employees
			HLP_fullNameLable:"Text for add or edit employees",
			HLP_emp_EmailLable:"Emil specific to employee",
			HLP_nationalNumberLable:"ID Number Special To the employee",
			HLP_departmentIdLable:"Add and edit departments",
			HLP_emp_MobileLable:"No. special to the employee",
			HLP_managerIdLable:" Shows department manager ",
			HLP_degreeLable:"Job title to employee in Department",
			HLP_specfializationLable:"All tasks for employee",
			HLP_userIdLable:"User ID for sign in system",
			HLP_jobTitleLable:"Job title, Nature of work",
			HLP_employeeIdLable:"No. reserved for employee",
			HLP_isActiveLable:"Is the employee working?",
			HLP_qualificationLable:"The name of level university degree to employee",
			HLP_RIGHT_SCAN_BLACK_Lable:"Print the document using the black color",
			HLP_RIGHT_SCAN_GRAY_Lable:"صلاحية تُعطى للموظف المعني لاستخدام الماسح الضوئي الرمادي",
			HLP_RIGHT_SCAN_COLOR_Lable:"صلاحية تُعطى للموظف المعني لاستخدام الماسح الضوئي الملون",
			HLP_RIGHT_SEND_OUTGOING_WITH_OLD_DATE_Lable:"Send correspondence in the old date",
			HLP_RIGHT_CREATE_GENERALIZATIONS_Lable:"صلاحية تُعطى للموظفين المعنيين لمخاطبة جميع الموظفين ( صلاحية خاصة بالمدراء).",
			HLP_RIGHT_SEND_WITHOUT_ATTACHMENTS_Lable:"صلاحية الارسال المحدد للوارد والصادر بدون مرفقات وتُحدد لبعض الموظفين المعنيين بذالك",
			HLP_RIGHT_CREATE_STATISTICAL_REPORTS_Lable:"صلاحية لانشاء التقارير الاحصائية (تُحدد لبعض الموظفين الذين لديهم صلاحية لذالك)",
			HLP_RIGHT_FOLLOWUP_REMINDER_Lable:"صلاحية تُعطى لبعض الموظفين المعنيين بالتذكير بمتابعة المعاملة",
			HLP_RIGHT_DEPT_SEARCH_OPTION_Lable:"صلاحية الوصول لمعاملات الادارة باكملها وتحدد لبعض الموظفين المعنيين بذالك",
			HLP_RIGHT_MAIN_DEPARTMENT_MANAGER_Lable:"The validity of the agency director",
			HLP_RIGHT_EDIT_OUTGOING_Lable:"صلاحية تُعطى للتعديل على معاملات الصادر الخارجي تُحدد لبعض الموظفين المعنيين بذالك",
			HLP_RIGHT_EDIT_INCOMING_Lable:"صلاحية تعطى للتعديل على معاملات الوارد الخارجي تحدد لبعض الموظفين المعنيين بذالك",
			HLP_RIGHT_EDIT_INTERNAL_Lable:"Editing for internal correspondences",
			HLP_RIGHT_FULL_SEARCH_OPTION_Lable:"صلاحية الوصول لمعاملات الوزارة باكملها وتُحدد لبعض الموظفين المعنيين بذالك",
			HLP_RIGHT_MANAGER_PERMISSION_Lable:"صلاحية تعطى لمدير محدد للادارة في المراسلات ",
			HLP_RIGHT_SHOW_CONFIDENTIALITY_SECURE_Lable:"Manager special to view secure correspondence  ",
			HLP_RIGHT_SHOW_CONFIDENTIALITY_VERY_SECURE_Lable:"صلاحية تُعطى لبعض المدراء والموظفين للاطلاع على المعاملات السرية جدا",
			HLP_RIGHT_SHOW_CONFIDENTIALITY_EXTREME_SECURE_Lable:"صلاحية تعطى لمدير محدد للادارة في المراسلات ",
			HLP_RIGHT_COMMUNICATE_ALL_EMPLOYEE_Lable:"صلاحية تُعطى للموظفين المعنيين لمخاطبة جميع الموظفين ( صلاحية خاصة بالمدراء).",
			HLP_RIGHT_EDIT_CORR_DETAILS_Lable:"صلاحية تُعطى للتعديل على معلومات المعاملة تُحدد للموظفين المعنيين بذالك ",
			HLP_RIGHT_EDIT_CORR_ATTACHMENTS_Lable:"صلاحية تعديل واضافة والغاء مرفقات من معاملات محددة تحدد لبعض الموظفين المعنيين بذالك",
			HLP_RIGHT_EDIT_CORR_RESEND_Lable:"صلاحية اعادة ارسال او تعديل المعاملات",
			HLP_RIGHT_END_CORRESPONDENCE_Lable:"صلاحية الحفظ والانهاء للمعاملة تُعطى للموظفين المعنيين بذالك",
			HLP_RIGHT_DELETE_HISTORY_AND_WORITEMS_Lable:"صلاحية تعطى لموظفيين معنيين بالتحكم في سجل الاحالات والحذف منها جهات مراد حذفها",
			HLP_RIGHT_REMINDER_MESSAGE_Lable:"صلاحية تُعطى للموظف لامكانية اضافة رسالة تذكير",
			HLP_RIGHT_DEADLINE_Lable:"صلاحية تُعطى للموظفين المعنيين لتحديد اخر موعد لانهاء المعاملة ",
			HLP_HasbackupEmployeeLable:"لاختيار الموظف البديل من القائمة ",
			HLP_BackupFromDate:"تاريخ اول يوم عمل للموظف البديل ",
			HLP_backupEndDateLable:"تاريخ اخر يوم عمل للموظف البديل",
			
			//Manage Departments
			HLP_canAccessSystemLable:"ظهور او اخفاء الادارة من النظام",
			HLP_rep_full_nameLable:"اظهار او اضافة نائب مدير الادارة المعنية",
			HLP_manager_full_name_arLable:"اظهار او اضافة مدير ادارة معينة ",
			HLP_departmentNameLable:"اظهار او اضافة ادارة معينة",
			HLP_RIGHT_EXPORT_Lable:"صلاحية لتصدير المعاملات تحدد على مستوى الادارة باكملها",
			HLP_RIGHT_CREATE_OUTGOING_Lable:"صلاحية لانشاء معاملات صادر خارجي تحدد على مستوى الادارة باكملها",
			HLP_RIGHT_CREATE_INCOMING_Lable:"صلاحية لانشاء معاملات وارد خارجي تحدد على مستوى الادارة باكملها",
			HLP_RIGHT_CREATE_INTERNAL_Lable:"صلاحية لانشاء معاملات داخلية تحدد على مستوى الادارة باكملها",
			HLP_RIGHT_Department_Represented_Lable:"صلاحية استلام المعاملات تحدد لممثل الادارة فقط",
			HLP_RIGHT_CREATE_DECESIONS_Lable:"صلاحية تعطى لبعض الموظفين المعنيين بانشاء القرارات",
			HLP_RIGHT_CREATE_CIRCULARS_Lable:"صلاحية انشاء تعاميم تحدد على مستوى الادارة باكملها",
			HLP_enable_Shared_Inbasket_lable:"تفعيل او الغاء الادارة التابعة لها الادارة الحالية",
			HLP_departmentQueueNameLable:"رقم محجوز للادارة الحالية",
			HLP_queueNameLable:"الادارة التابعة (الادارة الام)للادارة الحالية",
			
			//Manage Public Inbasket
			HLP_WorkQueues_Lable:"قائمة لانتظار الاعمال",
			HLP_ApplicationSpaces_Lable:"",
			HLP_queueNameLable:"",
			HLP_RolesName_English_Lable:"",
			HLP_RolesName_Arabic_Lable:"",
			HLP_departmentQueueName_English_Lable:"",
			HLP_departmentQueueName_Arabic_Lable:"",
			
			//Manage Public Inbasket Members
			HLP_Shared_Inbasket:"لاختيار الصندوق المشترك للادارة الحالية من القائمة",
			HLP_departmentName:"لاختيار الادارة المراد اظهارها بقائمة الاعضاء",
			HLP_EmployeeName:"لاختيار اسم الموظف المراد اظهارة بقائمة الاعضاء",
			
			//Manage Committees
			HLP_COMMITTEENAME:"لاضافة لجنة محددة اعضائها",
			HLP_PRESIDENTNAME:"اختيار رئيس اللجنة المُحدد من القائمة ",
			HLP_STARTDATE:"تاريخ بداية اعمال اللجنة",
			HLP_ENDDATE:"تاريخ نهاية اعمال اللجنة",
			
			//Manage Committees Members
			HLP_EmployeeList:"",




	// added by Bashar 15-12-2016
Show_Orgnization_logo_on_Barcode_Lable:"Show Orgnization logo on Barcode Lable",
Show_Orgnization_logo_on_Enquiry_Ticket:"Show Orgnization logo on Enquiry Ticket",
Show_QR_Code_on_Internal_Correspondence_Barcode_Lable:"Show QR Code on Internal Correspondence Barcode Lable",
Show_QR_Code_on_Incoming_Correspondence_Barcode_Lable:"Show QR Code on Incoming Correspondence Barcode Lable",
Show_QR_Code_on_Outgoing_Correspondence_Barcode_Lable:"Show QR Code on Outgoing Correspondence Barcode Lable",
Show_BarCode_Image_on_Internal_Correspondence_Barcode_Lable:"Show BarCode Image on Internal Correspondence Barcode Lable",
Show_BarCode_Image_on_Incoming_Correspondence_Barcode_Lable:"Show BarCode Image on Incoming Correspondence Barcode Lable",
Show_BarCode_Image_on_Outgoing_Correspondence_Barcode_Lable:"Show BarCode Image on Outgoing Correspondence Barcode Lable",
Clear_Logo_Image:"Clear Logo Image",
Save_Setting:"Save Setting",	

Manage_Barcod_Lable_Images_Settings:"Manage Barcod Lable Images Settings",
Orgnization_Logo_For_Barcode_Lable:"Orgnization Logo For Barcode Lable",
Add_Orgnization_Logo :"Add Orgnization Logo to Be Used for this Application Desktop:",
Show_In_Document:"Active",
	
	Manage_Web_Editor_Header_Footer_Images_Settings:"Manage The Header and footer for the Documents generated from the Moamalat Correspondance Web_Editor",
WebEditor_Image_Type_Lable:"Type",
			WithAttachments:"With Correspondance' Attachments ",
			RELATION_EDIT:"Search and Link with other Correspondances",
						Error_EnterFullNameOrFirstCharacterOfHisName:"Enter LDAP Full Name Or First Character Of His LDAP Full Name",
							Error_HaveNotFoundSuchUserAccountInLdap:"Have Not Found Such User Account In Ldap",
								AdminHR_fullNameDB_LBL :"Employee Full Name",
			
			HLPAdmin_fullNameDB:"The Full Name",
			
			error_MessageForAttachmentOfMoamalat:"Cannot send this Correspondence without at least one Electronic Attachment!",
				Exported:"Exported",
				
							
					RELATION_TYPE_DECISIONS:"DECISIONS",
RELATION_TYPE_CIRCULARS:"CIRCULARS",
			error_no_CIRCULARS_transfered_workflow_found : "There is an error , as no transfered workflow found for Circular process",
error_URL_parameter_for_CIRCULARS_workClassName_is_missing:"URL parameter for Circular workClassName is missing",
error_no_DECISIONS_transfered_workflow_found : "There is an error , as no transfered workflow found for Decision process",
error_URL_parameter_for_DECISIONS_workClassName_is_missing:"URL parameter for Decision workClassName is missing",


create_new_internal_correspondence_label : " Create  New Internal Correspondence",
create_new_Registration_correspondence_label : " Create  New Registration Account",	
		Registration_correspondence_properties_setIntroText : "The Values that you enter for the New Registration Account properties can be used later on to search and find this account.",
	internal_correspondence_properties_setIntroText : "The Values that you enter for the internal Correspondence properties can be used later on to search and find this Correspondence.",
	create_new_circulate_correspondence : "Create New Circulate Correspondence",
	circulate_correspondence_properties_setIntroText : "The Values that you enter for the Circulate Correspondence properties can be used later on to search and find this Correspondence.",
	create_new_decision_correspondence : "Create New Decision Correspondence",
	create_new_decision_correspondence_properties_setIntroText :"The Values that you enter for the Decision Correspondence properties can be used later on to search and find this Correspondence.",
	create_new_outgoing_correspondence : "Create New Outgoing Correspondence",
	create_new_outgoing_correspondence_properties_setIntroText :"The Values that you enter for the Outgoing Correspondence properties can be used later on to search and find this Correspondence.",
	View_outgoing_correspondence : "View An Outgoing Correspondence",
	View_outgoing_correspondence_properties_setIntroText :"The Values that entered for this Outgoing Correspondence properties can be used later on to search and find this Correspondence.",
	View_Internal_correspondence : "View An Internal Correspondence",
	View_Internal_correspondence_properties_setIntroText :"The Values that entered for this Internal Correspondence properties can be used later on to search and find this Correspondence.",
	View_Incoming_correspondence : "View An Incoming Correspondence",
	View_Incoming_correspondence_properties_setIntroText :"The Values that entered for this Incoming Correspondence properties can be used later on to search and find this Correspondence.",
	View_Circulate_correspondence : "View a Circulate Correspondence",
	View_Circulate_correspondence_properties_setIntroText :"The Values that entered for this Circulating Correspondence properties can be used later on to search and find this Correspondence.",
	View_Decision_correspondence : "View a Decision Correspondence",
	View_Decision_correspondence_properties_setIntroText :"The Values that entered for this Decision Correspondence properties can be used later on to search and find this Correspondence.",
	StepProcessor_Circulate_correspondence : "Process Circulating Correspondence Workflow",
	StepProcessor_Circulate_correspondence_setIntroText : "Those Values that  entered for the Circulating Correspondence properties can be used to search and find this Correspondence.",
	StepProcessor_Decision_correspondence : "Process Decision Correspondence Workflow",
	StepProcessor_Decision_correspondence_setIntroText : "Those Values that  entered for the Decision Correspondence properties can be used to search and find this Correspondence.",
	create_new_incoming_correspondence : "Create New Incoming Correspondence",
	create_new_incoming_correspondence_properties_setIntroText :"The Values that you enter for the Incoming Correspondence properties can be used later on to search and find this Correspondence.",
	
	stepProcessor_unified_actions_on_set_of_Correspondence:"Unified Action on set of Correspondence",
	stepProcessor_unified_actions_on_set_of_Correspondence_setIntroText : "This Feature Allow you to take unified action or set of Correspondence ",

	
	StepProcessor_internal_correspondence : "Process Internal Correspondence Workflow",
	StepProcessor_internal_correspondence_setIntroText : "Those Values that  entered for the internal Correspondence properties can be used to search and find this Correspondence.",
	StepProcessor_outgoing_correspondence : "Process Outgoing Correspondence Workflow",
	StepProcessor_outgoing_correspondence_setIntroText : "Those Values that  entered for the outgoing Correspondence properties can be used to search and find this Correspondence.",
	StepProcessor_incoming_correspondence : "Process Incoming Correspondence Workflow",
	StepProcessor_incoming_correspondence_setIntroText : "Those Values that  entered for the Incoming Correspondence properties can be used to search and find this Correspondence.",
	new_internal_correspondence_label :"New Internal Correspondence",
	new_circulate_correspondence_label :"New Circulate Correspondence",
	new_decision_correspondence_label :"New Decision Correspondence",
	new_outgoing_correspondence_label :"New Outgoing Correspondence",
	new_incoming_correspondence_label :"New Incoming Correspondence",


Viewing_Internal_correspondence : "Viewing an Internal Correspondence",
Viewing_Incoming_correspondence : "Viewing an Incoming Correspondence",
Viewing_Circulate_correspondence :"Viewing a Circulate Correspondence",
Viewing_Decision_correspondence : "Viewing a Decision Correspondence",
Viewing_outgoing_correspondence : "Viewing an Outgoing Correspondence",	
	
	
	
Lunching_Internal_correspondence : "Lunching an Internal Correspondence",
Lunching_Incoming_correspondence : "Lunching an Incoming Correspondence",
Lunching_Circulate_correspondence :"Lunching a Circulate Correspondence",
Lunching_Decision_correspondence : "Lunching a Decision Correspondence",
Lunching_outgoing_correspondence : "Lunching an Outgoing Correspondence",

Editing_Internal_correspondence : "Editing an Internal Correspondence",
Editing_Incoming_correspondence : "Editing an Incoming Correspondence",
Editing_Circulate_correspondence :"Editing a Circulate Correspondence",
Editing_Decision_correspondence : "Editing a Decision Correspondence",
Editing_outgoing_correspondence : "Editing an Outgoing Correspondence",


Completing_Internal_correspondence : "Completing an Internal Correspondence",
Completing_Incoming_correspondence : "Completing an Incoming Correspondence",
Completing_Circulate_correspondence :"Completing a Circulate Correspondence",
Completing_Decision_correspondence : "Completing a Decision Correspondence",
Completing_outgoing_correspondence : "Completing a Outgoing Correspondence",
		



VIEW_CORRESPONDENCE: "View Correspondence",
EDIT_CORRESPONDENCE: "Edit Correspondence",
DETAILS_CORRESPONDENCE: "Track Correspondence",
Lunch_New_CORRESPONDENCE : "Lunch New Correspondence",
COmplete_CORRESPONDENCE  : "Complete Correspondence",

Employees_label : "Employees",
Find_Employees_label : "Find Employee",
Search_Label : "Find",
Committee_Description_Label : "Committee Description",
Update_Logo_Label : "Update Logo",
Correspondence_Type_Label : "Correspondence Type",
Select_Department_Label : "Select Department",
Search_By_Label : "Search By",
Employee_Label : "Employee",
Department_Label : "Department",
Select_Employee_Label : "Select Employee",

All_Departments: "All Departments",
My_Favorites_list:"My Favorites list",
My_Favorites_list_Header:"My Favorites list",
Custome_List:"Predefined list",
Custome_List_header:"Predefined list",
error_on_Select_Delegating_Employee:"Has not sellected the Delegated Employee During your absent"



	

			
});